engines:
  brakeman:
    enabled: false

exclude_patterns:
  - "spec/"
  - "db/"
  - ".*"
  - "Dockerfile"
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"
  - "Rakefile"
  - "**/*.ico"
  - "**/*.erb"
  - "config.ru"
  - "*.yml"
  - "*.sql"
  - "script/"
