services:
  - docker

env:

before_install:
  # Let's stop postgresql
  - sudo service postgresql stop
  # wait for postgresql to shutdown
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done

  - docker-compose build app
  - HANAMI_ENV=test  docker-compose run app hanami db prepare

script:
  - docker-compose run app rspec
