version: '3.1'

services:
  pg:
    image: postgres:9.6.11
    ports:
      - "5432:5432"

  app:
    build: ./
    tty: true
    stdin_open: true
    command: /bin/sh -c "bundle exec hanami server --host=0.0.0.0 --port 80"
    ports:
      - "3000:80"
    links:
      - pg
    volumes:
      - .:/usr/src/app
    depends_on:
      - pg
    entrypoint: ./script/wait_for_pg.sh pg 5432
